In [6]:
import numpy as np



In [7]:
benimListem= [[10,20,30],[20,30,40],[40,50,60]]
benimMatrixDizim=np.array(benimListem)
print(benimMatrixDizim)

[[10 20 30]
 [20 30 40]
 [40 50 60]]


In [8]:
a=benimMatrixDizim[0]
print(a)

[10 20 30]


In [9]:
benimMatrixDizim[1][2] == benimMatrixDizim[1,2] #output 40


c=benimMatrixDizim[1:,2] #output [40 60]

d=benimMatrixDizim[2:,2] #output [60]

print(c)
print(d)

[40 60]
[60]


In [10]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]
yeniMatrix=np.array(yeniListe)

#peki ben istediğim indexleri çekebiliyor muyum ? 

print(yeniMatrix[[0,2,4]]) #burada bana 0-2-4 indexleri verir.

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
