In [7]:
import numpy as np


In [2]:
#Random
a=np.random.randn(4)
print(a)


[ 0.72742137 -1.04156428  1.4518943  -0.15832988]


In [3]:
#bunu matrix olarakta oluşturabiliyoruz.
b=np.random.randn(4,4)
print(b)

[[ 0.69672056 -0.37126572  0.80665794  1.40582751]
 [ 0.25313833 -0.54414669  1.06211568 -1.14560875]
 [-0.77791596 -0.1297958   0.71052721 -0.28805989]
 [ 0.39973225  0.39064983 -0.14174102  0.58831599]]


In [4]:
#peki rastgele bir sayı istersek belli bir aralıkta.
c=np.random.randint(1,20) # birinci parametre başlangıc, diğerini de son.
print(c)

3


In [5]:
#peki belli bir aralıkta birkaç sayı istersek..
d=np.random.randint(1,205,7)
print(d)

[ 81 197 108  50 148 116 101]


In [6]:

e=np.arange(30)
print(e)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
