In [9]:
import numpy as np


In [10]:
#mesela benim tek bir tane dizi olan dizimi ben matrixe çevirebilir miyim ? 

benimNumpyDizi=np.arange(0,30)
print(benimNumpyDizi)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [11]:
#eğer ben .reshape() fonksiyonunu ile bunu yapıyorum ve kullanmam lazım.
a=benimNumpyDizi.reshape(6,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [12]:
#eğer ben bu dizinin max değerini bulmaya çalışşsam:

b=benimNumpyDizi.max()
print(b)

29


In [16]:
#bunları yapmak için illa bir sıralı bir diziye ihtiyac yok

c=benimRandomDizi=np.random.randint(10,58,7)
print(c)

[36 28 56 39 45 53 38]


In [14]:
d=benimRandomDizi.max()
e=benimRandomDizi.min()
print(d,e)

54 27


In [15]:
#peki bunların hangi index'te olduklarını nasıl öğrenebilrim

f=benimRandomDizi.argmin()
print(f)

4
