In [2]:
import numpy as np

In [ ]:
#numpy'da arrays'lerde(diziler) başlicaz.
#numpy'in dizileri (arrays'ları) çok önemli he.


benimListem=[20,30,40]

i=np.array(benimListem)
print(type(i))
#liste içerisinde liste 'de oluşturabiliriz.

#yani ilk önce normal bi matrixListesi oluşturalım.

matrixListesi= [[10,20,30],[20,30,40],[30,40,50]]
matrixListesi[1][0] #yaparsam bana 20 vereceğini çocuk bile bilir.


np.array(matrixListesi) #yazarsam şayet bana matrix şeklinde verecektir.




In [11]:
#mesela listeye çevirmek için 1'den 10'a kadar sayıları list(range(0,10)) yazmamız yeterliydi.
#ŞİMDİ ARANGE'i görücez.


np.arange(0,10)  #yukarıdaki ile aynı çıktıyı verecektir.


#şimdi LINSPACE'i görelim.


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#şimdi LINSPACE'i görelim.


np.linspace(0,10,20) #ilk parametre baş. ikincisi son parametre , üçüncüsü ise 20 tane eş aralık bırakma anlamına geliyor.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [6]:
#np.eye yapısı soldan sağa doğru 1'li bir matriks oluşturur.

np.eye(10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.eye(3) #aradaki farklardan anlayacağını düşünüyorum..

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])