In [1]:
import numpy as np


#bazı şeylerin de değişmemesi için copy olması için.. 
ornekDizi=np.arange(0,24)
ornekDiziKopyası=ornekDizi.copy()

ornekDiziKopyasıSlicing=ornekDiziKopyası[3:6]
ornekDiziKopyasıSlicing[:]=500

a=ornekDiziKopyası                                        #output 0   1   2 500 500 500   6   7   8   9  10  11  12  13  14  15  16  17 18  19  20  21  22  23
  
b=ornekDizi                                        #output 0   1   2 3 4 5   6   7   8   9  10  11  12  13  14  15  16  17 18  19  20  21  22  23


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[  0   1   2 500 500 500   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [2]:
benimDizim=np.arange(0,15)
print(benimDizim)

#dizilerle hemen hemen aynı mantık.

#ama eğer ben 
benimDizim[3:8] =-5
#yazarsak 3 ve 7 indexlerin arasından hepsini -5 yapıyor.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
#bazı şeylerin de değişmemesi için copy olması için.. 
ornekDizi=np.arange(0,24)
ornekDiziKopyası=ornekDizi.copy()

ornekDiziKopyasıSlicing=ornekDiziKopyası[3:6]
ornekDiziKopyasıSlicing[:]=500

In [4]:
a=ornekDiziKopyası                                        #output 0   1   2 500 500 500   6   7   8   9  10  11  12  13  14  15  16  17 18  19  20  21  22  23
    
b=ornekDizi                                        #output 0   1   2 3 4 5   6   7   8   9  10  11  12  13  14  15  16  17 18  19  20  21  22  23

In [5]:
a

array([  0,   1,   2, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [6]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])